# Local dev overrides
services:
  web: &web
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.web/.env
      - ./.envs/.local/.db/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    volumes:
      - django_embrace_local_db_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5


volumes:
  django_embrace_local_db_data:
