# Local dev overrides
services:
  web: &web
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.web/.env

  db:
    volumes:
      - ${ENVIRONMENT}_db_data:/var/lib/postgresql/data
      - ${ENVIRONMENT}_db_data_backups:/backups
    env_file:
      - ./.envs/.local/.db/.env

  celeryworker:
    <<: *web

  celerybeat:
    <<: *web

  flower:
    <<: *web

volumes:
  local_db_data:
  local_db_data_backups:
