site_name: Hello Python on steroids
repo_url: https://github.com/ivanprytula/hello-python-on-steroids
repo_name: ivanprytula/hello-python-on-steroids
docs_dir: docs/
# site_dir: ./docs_site/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import os"
            - "import django"
            - "os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'django_project.settings.development')"
            - "django.setup()"
