# ==== Pytest ====
[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--ds=django_project.settings.test_runner --reuse-db --cov-config=config/coverage.ini --cov=config_core/ --cov-branch"
python_files = [
    "test_*.py",
]
required_plugins = ["pytest-django", "pytest-xdist"]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
]
markers = [
    # dummy markers for testing
    "custom_mark: some information of your mark",
    "foo",
    "bar",
    # conftest.py reorders tests moving slow ones to the end of the list
    "slow",
]


# ==== Coverage ====
[tool.coverage.run]
# include = ["co/**"]
omit = [
    ".venv/*",
    "manage.py",
    "*/tests/*",
    "*migrations*",
]
plugins = ["django_coverage_plugin"]
branch = true
source = ["."]

[tool.coverage.html]
directory = "htmlcov"


[tool.black]
line-length = 119
target-version = ['py311']
skip-string-normalization = false
exclude = '''
(
  /(
    | \.git
    | node_modules
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 5
balanced_wrapping = true
known_django = 'django'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
known_first_party = [
    "django_project",
]
skip = [".venv/", "venv", "node_modules"]


[tool.mypy]
# The mypy configurations: https://mypy.readthedocs.io/en/latest/config_file.html
python_version = "3.11"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true

plugins = [
  "mypy_django_plugin.main",
]


[tool.django-stubs]
django_settings_module = "django_project.settings.test_runner"


[tool.bandit]
exclude_dirs = ["tests"]


[tool.djlint]
indent = 2
profile="django"
max_line_length=120
blank_line_after_tag="endblock,extends,load"
format_css=true
format_js=true
use_gitignore=true
ignore="H030,H031,H017"
exclude="base-email.html"

[tool.djlint.js]
indent_size=2

[tool.djlint.css]
indent_size=2


[tool.ruff]
line-length = 120
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = ["E501", "E741"]
