# Generated by Django 4.2.5 on 2023-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModelName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "my_field_name",
                    models.CharField(
                        help_text="Enter field documentation", max_length=20, verbose_name="some common field name"
                    ),
                ),
            ],
            options={
                "verbose_name": "my-model-name",
                "verbose_name_plural": "my-model-names",
                "ordering": ["-my_field_name"],
            },
        ),
    ]
