# Generated by Django 4.2.5 on 2023-09-18 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_post_author_alter_post_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
